name: blutfest # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.4.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Fight of hordes of zombiez using items, perks and weapons.  # 79 char long summary
description: |
 A Crimsonland clone inspired by the unfished and no longer maintained FOSS-Game Bloodworks. You fight of hordes of zombiez using items, perks and weapons. Try to survive as long as possible.
 Features:
 - 10+ Wepaons
 - 30+ Perks
 - 10 Items

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  blutfest-game:
    plugin: dump
    source: gamefiles/
    after: [desktop-glib-only]
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libpulse0
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libasound2
  desktop-glib-only:  
        build-packages:
          - libglib2.0-dev
        plugin: make
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        stage-packages:
          - libglib2.0-bin

apps:
  blutfest:
    command: bin/desktop-launch $SNAP/Blutfest.bin
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    plugs:
      - opengl
      - network
      - network-bind
      - pulseaudio
      - x11
      - desktop
      - joystick
